apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db-clients
  namespace: network-policy
spec:
  podSelector:
    matchLabels:
      app: mariadb-server
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector: {}
        namespaceSelector:
          matchLabels:
            allowing: db-clients
  ports:
    - port: 3306
      protocol: TCP