apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: eb6e9c5e-3ed9-4e37-b3de-7fc0d994c1d2
    kubevirt.io/domain: vm-k8s-master01
    kubevirt.io/nodeName: master03
    kubevirt.io/size: small
    network.kubevirt.io/headlessService: headless
    vm.kubevirt.io/name: vm-k8s-master01
  name: virt-launcher-vm-k8s-master01-4wl9r
spec:
  ports:
  - name: 22-tcp
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/domain: vm-k8s-master01
  type: LoadBalancer
status:
  loadBalancer: {}
