apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 7d624e43-ed01-41c5-b37b-774af0adc04a
    kubevirt.io/domain: vm-k8s-master02
    kubevirt.io/nodeName: master02
    kubevirt.io/size: small
    network.kubevirt.io/headlessService: headless
    vm.kubevirt.io/name: vm-k8s-master02
  name: virt-launcher-vm-k8s-master02-f84hn
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 22-tcp
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: vm-k8s-master02
  type: LoadBalancer
status:
  loadBalancer: {}
